"""Initial schema

Revision ID: 197f1d99a41e
Revises: 
Create Date: 2025-12-24 22:56:07.756009+00:00

"""
from alembic import op
import sqlalchemy as sa
from app.database_types import JSON, GUID


# revision identifiers, used by Alembic.
revision = '197f1d99a41e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('job_url', sa.String(), nullable=False),
    sa.Column('apply_url', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('location_text', sa.String(), nullable=True),
    sa.Column('work_mode', sa.String(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('description_clean', sa.Text(), nullable=True),
    sa.Column('skills', JSON(), nullable=True),
    sa.Column('has_been_applied_to', sa.Boolean(), nullable=False),
    sa.Column('last_applied_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('magic_link_token', sa.String(), nullable=True),
    sa.Column('magic_link_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('application_runs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('settings_snapshot', JSON(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_tasks',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('run_id', GUID(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sa.String(), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_state_change_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['application_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'job_id', name='uq_run_job')
    )
    op.create_index('idx_tasks_queue', 'application_tasks', ['run_id', 'state', 'priority', 'queued_at'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('task_id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('form_data', sa.JSON(), nullable=False),
    sa.Column('preview_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('approval_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['application_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_approval_token'), 'approval_requests', ['approval_token'], unique=True)
    op.create_index(op.f('ix_approval_requests_task_id'), 'approval_requests', ['task_id'], unique=True)
    op.create_index(op.f('ix_approval_requests_user_id'), 'approval_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_requests_user_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_task_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_approval_token'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index('idx_tasks_queue', table_name='application_tasks')
    op.drop_table('application_tasks')
    op.drop_table('application_runs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('job_postings')
    # ### end Alembic commands ###
