"""add_user_profile_and_security_fields

Revision ID: c1988511bab1
Revises: 197f1d99a41e
Create Date: 2025-12-25 19:10:44.649332+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1988511bab1'
down_revision = '197f1d99a41e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'ADMIN', name='user_role'), nullable=False))
    op.add_column('users', sa.Column('last_login_ip', sa.String(length=45), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('account_locked_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('address_street', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('address_city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('address_state', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('address_zip', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('address_country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('github_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('portfolio_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('resume_path', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('resume_uploaded_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('resume_filename', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('resume_size_bytes', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('mandatory_questions', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_users_magic_link_token'), 'users', ['magic_link_token'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_magic_link_token'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'mandatory_questions')
    op.drop_column('users', 'resume_size_bytes')
    op.drop_column('users', 'resume_filename')
    op.drop_column('users', 'resume_uploaded_at')
    op.drop_column('users', 'resume_path')
    op.drop_column('users', 'portfolio_url')
    op.drop_column('users', 'github_url')
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'address_country')
    op.drop_column('users', 'address_zip')
    op.drop_column('users', 'address_state')
    op.drop_column('users', 'address_city')
    op.drop_column('users', 'address_street')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'account_locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'last_login_ip')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
